// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctahqfbyzgvznrlvhlpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0YWhxZmJ5emd2em5ybHZobHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjcyMDYsImV4cCI6MjA1NzI0MzIwNn0.zCbppdXGWbWOaQm6G2V_Xf7MMMax23ErHxaVGQjQfGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);